### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by codeskyblue** [openatx/go-minicap#1]
- [ ] windows and unix system use different jpeg lib
- [x] extract goadb driver
- [ ] Simplify the code
